src/nupur/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
]

src/store/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name ='home'),
    path('aboutus/', views.Aboutus, name ='aboutus'),
    path('login/', views.userLogin, name ='login'),
    path('register/', views.register, name = "register"),
    path('dashboard/', views.dashboard, name = "dashboard"),
    path('profile/', views.profile, name = "profile"),
    path('dashboard-messages/', views.dashboard_messages, name = "dashboard-meassages"),
    path('dashboard-bookings/', views.dashboard_bookings, name = "dashboard-bookings"),
    path('dashboard-wallet/', views.dashboard_wallet, name = "dashboard-wallet"),
    path('dashboard-listing/', views.dashboard_listing, name = "dashboard-listing"),
    path('dashboard-reviews/', views.dashboard_reviews, name = "dashboard-reviews"),
    path('dashboard-bookmarks/', views.dashboard_bookmarks, name = "dashboard-bookmarks"),
    path('dashboard-addlisting/', views.dashboardAddlist , name = "dashboard-addlisting"),
    path('dashboard-myprofile/', views.dashboard_profile , name = "dashboard-myprofile"),


]

src/store/models.py
from django.db import models
from django.conf import settings

class Profile(models.Model):
    firstname  = models.CharField(max_length=100)
    phone = models.CharField(max_length=11)
    email = models.EmailField(max_length=100)
    notes = models.TextField(max_length=255)
    twitter = models.CharField(max_length=100)
    facebook = models.CharField(max_length=100)
    google = models.CharField(max_length=100)
    image = models.ImageField(upload_to ='profile_image', blank = True)

    def __str__(self):
        return self.firstname

src/store/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Profile
class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username' ,'email', 'password1']

class Profileform(ModelForm):
    class Meta:
        model = Profile
        fields = [
            'firstname',
            'phone',
            'email',
            'notes',
            'twitter',
            'facebook',
            'google',
            'image',
        ]

src/store/views.py
import requests
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib import messages
from .forms import CreateUserForm
from .forms import Profileform

#home view
def home(request):
    return render(request, 'index.html')


def Aboutus(request):
    return render(request, 'about.html')
#UserLogin
def userLogin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.info(request, 'Username or Password is incorrect')
    context = {}
    return render(request, 'index.html', context)


#Registration page
def register(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    context = {'form': form}
    return render(request, "my-account.html", context)


@login_required
def dashboard(request):
    return render(request, 'dashboard.html')

def dashboard_messages(request):
    return render(request, 'dashboard-messages.html')

def dashboard_bookings(request):
    return render(request, 'dashboard-bookings.html')

def dashboard_wallet(request):
    return render(request, 'dashboard-wallet.html')

def dashboard_listing(request):
    return render(request, 'dashboard-my-listings.html')

def dashboard_reviews(request):
    return render(request, 'dashboard-reviews.html')

def dashboard_bookmarks(request):
    return render(request, 'dashboard-bookmarks.html')

def dashboardAddlist(request):
    return render(request, 'dashboard-add-listing.html')

def dashboard_profile(request):
    return render(request, 'dashboard-my-profile.html')


def profile(request):
    form = Profileform()
    if request.method == 'POST':
        form = Profileform(request.POST)
        if form.is_valid():
            form.save()
            return redirect('dashboard')
    context = {'form': form}
    return render(request, "dashboard-my-profile.html", context)

src/store/templates/comming-soon.html
<!DOCTYPE html>
<html style="height:100%">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" >
<title> 404 Not Found
</title></head>
<body style="color: #444; margin:0;font: normal 14px/20px Arial, Helvetica, sans-serif; height:100%; background-color: #fff;">
<div style="height:auto; min-height:100%; ">     <div style="text-align: center; width:800px; margin-left: -400px; position:absolute; top: 30%; left:50%;">
        <h1 style="margin:0; font-size:150px; line-height:150px; font-weight:bold;">404</h1>
<h2 style="margin-top:20px;font-size: 30px;">Not Found
</h2>
<p>The resource requested could not be found on this server!</p>
</div></div></body></html>

src/store/templates/dashboard-bookmarks.html
{% extends "dash-home.html" %}
{% block content %}

<!-- Wrapper -->
<div id="wrapper">


<!-- Dashboard -->
<div id="dashboard">

	<!-- Navigation
	================================================== -->

	<!-- Responsive Navigation Trigger -->
	<a href="#" class="dashboard-responsive-nav-trigger"><i class="fa fa-reorder"></i> Dashboard Navigation</a>
	
	<div class="dashboard-nav">
		<div class="dashboard-nav-inner">

			<ul data-submenu-title="Main">
				<li><a href="/dashboard/"><i class="sl sl-icon-settings"></i> Dashboard</a></li>
				<li><a href="/dashboard-messages/"><i class="sl sl-icon-envelope-open"></i> Messages <span class="nav-tag messages">2</span></a></li>
				<li><a href="/dashboard-bookings/"><i class="fa fa-calendar-check-o"></i> Bookings</a></li>
				<li><a href="/dashboard-wallet/"><i class="sl sl-icon-wallet"></i> Wallet</a></li>
			</ul>
			
			<ul data-submenu-title="Listings">
				<li><a><i class="sl sl-icon-layers"></i> My Listings</a>
					<ul>
						<li><a href="/dashboard-listing/">Active <span class="nav-tag green">6</span></a></li>
						<li><a href="/dashboard-listing/">Pending <span class="nav-tag yellow">1</span></a></li>
						<li><a href="/dashboard-listing/">Expired <span class="nav-tag red">2</span></a></li>
					</ul>	
				</li>
				<li><a href="/dashboard-reviews/"><i class="sl sl-icon-star"></i> Reviews</a></li>
				<li class="active"><a href="/dashboard-bookmarks/"><i class="sl sl-icon-heart"></i> Bookmarks</a></li>
				<li><a href="/dashboard-addlisting/"><i class="sl sl-icon-plus"></i> Add Listing</a></li>
			</ul>	

			<ul data-submenu-title="Account">
				<li><a href="/dashboard-myprofile/"><i class="sl sl-icon-user"></i> My Profile</a></li>
				<li><a href="index.html"><i class="sl sl-icon-power"></i> Logout</a></li>
			</ul>

		</div>
	</div>
	<!-- Navigation / End -->


	<!-- Content
	================================================== -->
	<div class="dashboard-content">

		<!-- Titlebar -->
		<div id="titlebar">
			<div class="row">
				<div class="col-md-12">
					<h2>Bookmarks</h2>
					<!-- Breadcrumbs -->
					<nav id="breadcrumbs">
						<ul>
							<li><a href="#">Home</a></li>
							<li><a href="#">Dashboard</a></li>
							<li>Bookmarks</li>
						</ul>
					</nav>
				</div>
			</div>
		</div>

		<div class="row">
			
			<!-- Listings -->
			<div class="col-lg-12 col-md-12">
				<div class="dashboard-list-box margin-top-0">
					<h4>Bookmarked Listings</h4>
					<ul>

						<li>
							<div class="list-box-listing">
								<div class="list-box-listing-img"><a href="#"><img src="images/listing-item-02.jpg" alt=""></a></div>
								<div class="list-box-listing-content">
									<div class="inner">
										<h3>Sticky Band</h3>
										<span>Bishop Avenue, New York</span>
										<div class="star-rating" data-rating="5.0">
											<div class="rating-counter">(23 reviews)</div>
										</div>
									</div>
								</div>
							</div>
							<div class="buttons-to-right">
								<a href="#" class="button gray"><i class="sl sl-icon-close"></i> Delete</a>
							</div>
						</li>

						<li>
							<div class="list-box-listing">
								<div class="list-box-listing-img"><a href="#"><img src="images/listing-item-04.jpg" alt=""></a></div>
								<div class="list-box-listing-content">
									<div class="inner">
										<h3>Burger House</h3>
										<span>2726 Shinn Street, New York</span>
										<div class="star-rating" data-rating="5.0">
											<div class="rating-counter">(31 reviews)</div>
										</div>
									</div>
								</div>
							</div>
							<div class="buttons-to-right">
								<a href="#" class="button gray"><i class="sl sl-icon-close"></i> Delete</a>
							</div>
						</li>

						<li>
							<div class="list-box-listing">
								<div class="list-box-listing-img"><a href="#"><img src="images/listing-item-06.jpg" alt=""></a></div>
								<div class="list-box-listing-content">
									<div class="inner">
										<h3>Think Coffee</h3>
										<span>215 Terry Lane, New York</span>
										<div class="star-rating" data-rating="5.0">
											<div class="rating-counter">(31 reviews)</div>
										</div>
									</div>
								</div>
							</div>
							<div class="buttons-to-right">
								<a href="#" class="button gray"><i class="sl sl-icon-close"></i> Delete</a>
							</div>
						</li>

					</ul>
				</div>
			</div>


			<!-- Copyrights -->
			<div class="col-md-12">
				<div class="copyrights">© 2019 Listeo. All Rights Reserved.</div>
			</div>
		</div>

	</div>
	<!-- Content / End -->


</div>
<!-- Dashboard / End -->


</div>
<!-- Wrapper / End -->


{% endblock content %}

src/store/templates/dashboard-invoice.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<title>Listeo Invoice</title>
	<link rel="stylesheet" href="{%static 'dashboard/css/invoice.css'%}">
</head> 

<body>

<!-- Print Button -->
<a href="javascript:window.print()" class="print-button">Print this invoice</a>

<!-- Invoice -->
<div id="invoice">

	<!-- Header -->
	<div class="row">
		<div class="col-md-6">
			<div id="logo"><img src="{%static'images/logo.png%}" alt=""></div>
		</div>

		<div class="col-md-6">	

			<p id="details">
				<strong>Order:</strong> #00124 <br>
				<strong>Issued:</strong> 20/07/2019 <br>
				Due 7 days from date of issue
			</p>
		</div>
	</div>


	<!-- Client & Supplier -->
	<div class="row">
		<div class="col-md-12">
			<h2>Invoice</h2>
		</div>

		<div class="col-md-6">	
			<strong class="margin-bottom-5">Supplier</strong>
			<p>
				Listeo Ltd. <br>
				21 St Andrews Lane <br>
				London, CF44 6ZL, UK <br>
			</p>
		</div>

		<div class="col-md-6">	
			<strong class="margin-bottom-5">Customer</strong>
			<p>
				John Doe <br>
				36 Edgewater Street <br>
				Melbourne, 2540, Australia <br>
			</p>
		</div>
	</div>


	<!-- Invoice -->
	<div class="row">
		<div class="col-md-12">
			<table class="margin-top-20">
				<tr>
					<th>Description</th>
					<th>Quantity</th>
					<th>VAT</th>
					<th>Total</th>
				</tr>

				<tr>
					<td>Extended Plan</td> 
					<td>1</td>
					<td>$0.00</td>
					<td>$9.00</td>
				</tr>
			</table>
		</div>
		
		<div class="col-md-4 col-md-offset-8">	
			<table id="totals">
				<tr>
					<th>Total Due</th> 
					<th><span>$9.00</span></th>
				</tr>
			</table>
		</div>
	</div>


	<!-- Footer -->
	<div class="row">
		<div class="col-md-12">
			<ul id="footer">
				<li><span>www.example.com</span></li>
				<li>office@example.com</li>
				<li>(123) 123-456</li>
			</ul>
		</div>
	</div>
		
</div>


</body>
</html>

src/store/templates/dashboard-my-profile.html
{% extends "dash-home.html" %}
{% block content %}
<!-- Wrapper -->
<div id="wrapper">



<!-- Dashboard -->
<div id="dashboard">

	<!-- Navigation
	================================================== -->

	<!-- Responsive Navigation Trigger -->
	<a href="#" class="dashboard-responsive-nav-trigger"><i class="fa fa-reorder"></i> Dashboard Navigation</a>
	
	<div class="dashboard-nav">
		<div class="dashboard-nav-inner">

			<ul data-submenu-title="Main">
				<li><a href="/dashboard/"><i class="sl sl-icon-settings"></i> Dashboard</a></li>
				<li><a href="/dashboard-messages/"><i class="sl sl-icon-envelope-open"></i> Messages <span class="nav-tag messages">2</span></a></li>
				<li><a href="/dashboard-bookings/"><i class="fa fa-calendar-check-o"></i> Bookings</a></li>
				<li><a href="/dashboard-wallet/"><i class="sl sl-icon-wallet"></i> Wallet</a></li>
			</ul>
			
			<ul data-submenu-title="Listings">
				<li><a><i class="sl sl-icon-layers"></i> My Listings</a>
					<ul>
						<li><a href="/dashboard-listing/">Active <span class="nav-tag green">6</span></a></li>
						<li><a href="/dashboard-listing/">Pending <span class="nav-tag yellow">1</span></a></li>
						<li><a href="/dashboard-listing/">Expired <span class="nav-tag red">2</span></a></li>
					</ul>	
				</li>
				<li><a href="/dashboard-reviews/"><i class="sl sl-icon-star"></i> Reviews</a></li>
				<li><a href="/dashboard-bookmarks/"><i class="sl sl-icon-heart"></i> Bookmarks</a></li>
				<li><a href="/dashboard-addlisting/"><i class="sl sl-icon-plus"></i> Add Listing</a></li>
			</ul>	

			<ul data-submenu-title="Account">
				<li class="active"><a href="/dashboard-myprofile/"><i class="sl sl-icon-user"></i> My Profile</a></li>
				<li><a href="index.html"><i class="sl sl-icon-power"></i> Logout</a></li>
			</ul>

	</div>
	</div>
	<!-- Navigation / End -->


	<!-- Content
	================================================== -->
	<div class="dashboard-content">

		<!-- Titlebar -->
		<div id="titlebar">
			<div class="row">
				<div class="col-md-12">
					<h2>My Profile</h2>
					<!-- Breadcrumbs -->
					<nav id="breadcrumbs">
						<ul>
							<li><a href="#">Home</a></li>
							<li><a href="#">Dashboard</a></li>
							<li>My Profile</li>
						</ul>
					</nav>
				</div>
			</div>
		</div>

		<div class="row">

			<!-- Profile -->
			<div class="col-lg-6 col-md-12">
				<div class="dashboard-list-box margin-top-0">
					<h4 class="gray">Profile Details</h4>
					<div class="dashboard-list-box-static">
						
						<!-- Avatar -->
						<div class="edit-profile-photo">
							<img src="images/user-avatar.jpg" alt="">
							<div class="change-photo-btn">
								<div class="photoUpload">
								    <span><i class="fa fa-upload"></i> Upload Photo</span>
								    <input type="file" class="upload" />
								</div>
							</div>
						</div>
	
						<!-- Details -->
						<div class="my-profile">
							<form method="POST">
								{% csrf_token %}
								<label>Your Name</label>
								<input type="text" name="firstname" maxlength="100" required="" id="id_firstname">

								<label>Phone</label>
								<input type="number" name="phone" required="" id="id_phone">

								<label>Email</label>
								<input type="email" name="email" maxlength="100" required="" id="id_email">

								<label>Notes</label>
								<textarea name="notes" cols="40" rows="10" maxlength="255" required="" id="id_notes"></textarea>

								<label><i class="fa fa-twitter"></i> Twitter</label>
								<input type="text" name="twitter" maxlength="100" required="" id="id_twitter">

								<label><i class="fa fa-facebook-square"></i> Facebook</label>
								<input type="text" name="facebook" maxlength="100" required="" id="id_facebook">

								<label><i class="fa fa-google-plus"></i> Google+</label>
								<input type="text" name="google" maxlength="100" required="" id="id_google">
							</form>
						</div>
	
						<button type = "submit "class="button margin-top-15">Save Changes</button>

					</div>
				</div>
			</div>

			<!-- Change Password -->
			<div class="col-lg-6 col-md-12">
				<div class="dashboard-list-box margin-top-0">
					<h4 class="gray">Change Password</h4>
					<div class="dashboard-list-box-static">

						<!-- Change Password -->
						<div class="my-profile">
							<label class="margin-top-0">Current Password</label>
							<input type="password">

							<label>New Password</label>
							<input type="password">

							<label>Confirm New Password</label>
							<input type="password">

							<button class="button margin-top-15">Change Password</button>
						</div>

					</div>
				</div>
			</div>


			<!-- Copyrights -->
			<div class="col-md-12">
				<div class="copyrights">© 2019 Listeo. All Rights Reserved.</div>
			</div>

		</div>

	</div>
	<!-- Content / End -->


</div>
<!-- Dashboard / End -->


</div>
<!-- Wrapper / End -->
{% endblock content %}

src/store/templates/footer.html
<footer class="footer-area">
<div class="footer-top">
    <div class="container">
        <div class="row">
            <div class="col-md-2 col-sm-4">
                <div class="footer-widget">
                    <h3 class="footer-title">our product</h3>
                    <ul class="product-list">
                        <li><a href="#">Freebee</a>
                        </li>
                        <li><a href="#">PSD Template</a>
                        </li>
                        <li><a href="#">HTML Template</a>
                        </li>
                        <li><a href="#">Wordpress Template</a>
                        </li>
                        <li><a href="#">Others Graphic</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-2 col-sm-4">
                <div class="footer-widget support-pd">
                    <h3 class="footer-title">support</h3>
                    <ul class="our-support">
                        <li><a href="#">General Support</a>
                        </li>
                        <li><a href="#">Community Forum </a>
                        </li>
                        <li><a href="#">Licenses </a>
                        </li>
                        <li><a href="#">Terms & Conditions </a>
                        </li>
                        <li><a href="#">Privacy Policy </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-2 col-md-offset-1 col-sm-4">
                <div class="footer-widget">
                    <h3 class="footer-title">company</h3>
                    <ul class="our-company">
                        <li><a href="about.html">About</a>
                        </li>
                        <li><a href="faq.html">Faq Page</a>
                        </li>
                        <li><a href="contact.html">Contact Us</a>
                        </li>
                        <li><a href="#">Copyright Notice</a>
                        </li>
                        <li><a href="#">Refund Policy</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-5 col-sm-9">
                <div class="footer-widget">
                    <h3 class="footer-title">Newsletter</h3>
                    <p>Want more Bootstrap themes & templates? Subscribe to our mailing list to receive an update when new items arrive!</p>
                    <form action="https://web.dotthemes.com/html/storola-demo/storola/action.php" class="subscribe-form">
                        <input type="email" placeholder="Your Mail here">
                        <button type="submit">subscribe</button>
                    </form>
                    <span class="community-count"><strong>3500125</strong>Community members</span>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="footer-buttom">
    <div class="container">
        <div class="row">
            <div class="col-sm-5 col-md-6 col-xs-12">
                <div class="copy-right">
                    <p>©Copyright 2018   |  Storola  |   All Rights Reserved.    </p>
                </div>
            </div>
            <div class="col-md-6 col-sm-7 col-xs-12">
                <div class="footer-social">
                    <ul>
                        <li class="fb"><a href="#"><i class="fa fa-facebook-square"></i>facebook</a>
                        </li>
                        <li class="gp"><a href="#"><i class="fa fa-google-plus"></i>Google+</a>
                        </li>
                        <li class="be"><a href="#"><i class="fa fa-behance"></i>behance</a>
                        </li>
                        <li class="tw"><a href="#"><i class="fa fa-twitter"></i>twitter</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
</footer>

src/store/templates/script.html
{% load static %}


<script src="{%static 'js/jquery.min.js'%}"></script>

<!-- Bootstrap Js 
==============================================================-->
<script src="{%static 'js/bootstrap.min.js'%}"></script>

<!-- Meanmenu Js 
==============================================================-->
<script src="{%static 'js/jquery.meanmenu.js'%}"></script>

<!-- Isotope Js 
==============================================================-->
<script src="{%static 'js/isotope.pkgd.min.js'%}"></script>

<!-- Steller Js 
==============================================================-->
<script src="{%static 'js/jquery.stellar.min.js'%}"></script>

<!-- Simple-sticker Js 
==============================================================-->
<script src="{%static 'js/jquery.simpleTicker.js'%}"></script>

<!-- Syotimer Js 
==============================================================-->
<script src="{%static 'js/jquery.syotimer.min.js'%}"></script>

<!-- Owl Carosel Js 
==============================================================-->
<script src="{%static 'js/owl.carousel.min.js'%}"></script>

<!-- Custom Js 
================================================================-->
<script src="{%static 'js/main.js'%}"></script>